services:
  frontend:
    build: ./front
    container_name: interview-frontend
    ports:
      - "8081:80"
    networks:
      - interview-network
    depends_on:
      - backend

  backend:
    build: .
    container_name: interview-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - interview-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  interview-network:
    driver: bridge
